# Generated by Django 2.1.1 on 2020-08-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenteDeCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('cuentas', models.ManyToManyField(to='cuentas.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=20000, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='gerentedecuentas',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentas.PerfilEmpleado'),
        ),
    ]
